In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [22]:
X_train.shape

(60000, 28, 28)

In [5]:
set(y_train)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [6]:
# 8비트 회색조 이미지 28*28px 크기, 총 7만개 데이터. 6:1 비율로 split, 총 10 클래스

전처리

In [7]:
X_train, X_test = X_train / 255.0, X_test / 255.0

In [25]:
X_train[0:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

# 모델생성

1. 모델정의(어떤 형태의 모델을 구현할 것인가)
2. 입력층 설정 : input shape, 형태 변환
3. 출력층 설정 : binary(출력형태가 1차원)/multiclass(각 필요한 클래스의 갯수만큼 설정) classification
4. 은닉층 설정 : 데이터의 차원, 정보를 변형해가며 연산할 수 있도록 설계
5. 모델 컴파일 : 최적화 함수, 손실 함수, 평가 지표 등을 설정
6. 예측
7. 검증

In [8]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),  # 입력층
        tf.keras.layers.Dense(128, activation="relu"),  # relu는 활성함수
        tf.keras.layers.Dropout(
            0.2
        ),  # hidden layer에서 랜덤하게 노드를 끔. CV랑 비슷한 개념, 딥러닝 모델의 과적합을 막기위해 사용.
        tf.keras.layers.Dense(
            10, activation="softmax"
        ),  # 출력층, 보고 싶은 클래스 수 넣으면 됨
    ]
)

c:\Users\user\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",  # 오차계산을 어떻게 할 것인가
    metrics=["accuracy"],
)

In [19]:
X_train[0:1].shape

(1, 28, 28)

In [29]:
predictions = model(X_train[10:11]).numpy()
predictions

array([[1.7271250e-17, 2.9914879e-09, 7.9442338e-12, 9.9999988e-01,
        1.5881202e-15, 3.9031793e-08, 1.6851758e-22, 9.5537278e-15,
        2.7119826e-09, 1.1957620e-07]], dtype=float32)

In [30]:
y_train[10]

3

In [31]:
tf.nn.softmax(predictions).numpy()

array([[0.08533675, 0.08533675, 0.08533675, 0.2319693 , 0.08533675,
        0.08533676, 0.08533675, 0.08533675, 0.08533675, 0.08533677]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[2:3], predictions).numpy()

2.3100011

In [14]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 850us/step - accuracy: 0.8657 - loss: 0.4730
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 856us/step - accuracy: 0.9548 - loss: 0.1532
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 830us/step - accuracy: 0.9658 - loss: 0.1110
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 855us/step - accuracy: 0.9740 - loss: 0.0873
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 846us/step - accuracy: 0.9771 - loss: 0.0729
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 850us/step - accuracy: 0.9785 - loss: 0.0645
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 852us/step - accuracy: 0.9814 - loss: 0.0587
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 853us/step - accuracy: 0.9841 - loss: 0.0479
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 856us/step - accuracy: 0.9854 - loss: 0.0437
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 837us/step - accuracy: 0.9866 - loss: 0.0409


In [15]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.9781 - loss: 0.0817


[0.06960257887840271, 0.9801999926567078]

In [16]:
model.predict(X_train[18:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[5.52318415e-05, 3.45161766e-08, 1.01054532e-07, 6.10449604e-07,
        1.42846845e-08, 4.60759271e-03, 9.95221555e-01, 1.89596383e-09,
        1.14569826e-04, 2.97343433e-07],
       [2.42869201e-13, 5.57349757e-08, 9.66411535e-14, 1.97199897e-05,
        1.89304035e-06, 1.37089785e-07, 6.18157445e-15, 6.91601872e-06,
        2.59090029e-07, 9.99971151e-01]], dtype=float32)