In [5]:
import numpy as np

array_1d = np.array([1, 2, 3])
# print(array_1d)

# 리스트의 특징
array_1d = np.array([1, 2, "3"])
# print(array_1d)

# 2차원 넘파이 배열 생성
array_2d = np.array([[1, 2], [3, 4]])
print(array_2d)

[[1 2]
 [3 4]]


In [12]:
zero_array = np.zeros(10)
print(zero_array)

zero_array_2d = np.zeros((5, 10))
print(zero_array_2d)

nine_array_2d = np.full((3, 3), 9)
print(nine_array_2d)

random_array = np.random.random(10)
print(random_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[0.472264   0.68697624 0.10352378 0.90577613 0.10676077 0.19513558
 0.92092183 0.96284669 0.41563234 0.72832749]


In [15]:
# 배열의 연산
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = array1 * array2

print(array3)  # 4 10 18

# 행렬 간 사이즈 같아야 연산 가능

array1_2d = np.array([[1, 2], [3, 4]])
array2_2d = np.array([[5, 6], [7, 8]])

print(array1_2d + array2_2d)
print(array1_2d * array2_2d)
print(array1_2d - array2_2d)
print(array1_2d % array2_2d)

[ 4 10 18]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[-4 -4]
 [-4 -4]]
[[1 2]
 [3 4]]


In [17]:
# 배열의 차원 크기
array_1d = np.zeros(12)
print(array_1d)
print(array_1d.shape)

array_2d = np.zeros((3, 3))
print(array_2d)
print(array_2d.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(12,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [18]:
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12])

print(array_1d.shape)  # (12,), 1차원 배열이며 12개의 값을 가진 배열


array_2d = array_1d.reshape((6, 2))
print(array_2d.shape)  # (6, 2), 2차원 배열이며 6행 2열의 배열
print(array_2d)

(12,)
(6, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 9 10]
 [11 12]]
